# Generated by Django 5.2.12 on 2026-04-03 20:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('src', models.URLField(blank=True, help_text='Public URL for image', max_length=2000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/images/')),
                ('youtube_id', models.CharField(blank=True, max_length=32)),
                ('file_src', models.URLField(blank=True, help_text='Direct MP4/stream URL or absolute path', max_length=2000)),
                ('video', models.FileField(blank=True, null=True, upload_to='gallery/videos/')),
                ('poster_src', models.URLField(blank=True, max_length=2000)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='gallery/posters/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=500)),
                ('duration_days', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('base_price', models.CharField(help_text='Display string e.g. TSh 1,196,000 per person (6+)', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('active', 'Active'), ('draft', 'Draft')], default='draft', max_length=20)),
                ('from_price', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('segment', models.CharField(choices=[('airport', 'Airport & hotel'), ('half_day', 'Half day'), ('full_day', 'Full day')], max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('from_price', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('draft', 'Draft')], default='active', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['segment', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('super_admin', 'Super admin'), ('admin', 'Admin'), ('editor', 'Editor')], default='editor', max_length=20)),
                ('privileges', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('invited', 'Invited')], default='active', max_length=20)),
                ('last_active', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_code', models.CharField(editable=False, max_length=32, unique=True)),
                ('guest_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('booking_type', models.CharField(choices=[('tour', 'Tour'), ('package', 'Package'), ('transfer', 'Transfer')], max_length=20)),
                ('item_name', models.CharField(help_text='Tour/package/transfer label shown in dashboard', max_length=500)),
                ('service_date', models.DateField()),
                ('party_size', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('new', 'New'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('estimated_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='safari.package')),
                ('tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='safari.tour')),
            ],
            options={
                'ordering': ['-service_date', '-created_at'],
            },
        ),
    ]
