# Generated by Django 5.2.4 on 2026-04-04 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safari', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='booking',
            name='additional_services',
            field=models.JSONField(blank=True, default=list, help_text='["Drone & photographer", ...]'),
        ),
        migrations.AddField(
            model_name='booking',
            name='adults',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='children',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='country',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='booking',
            name='custom_destination_request',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='customize_destination_request',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='dropoff_location',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='booking',
            name='flight_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='booking',
            name='hotel',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='language',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_time_note',
            field=models.CharField(blank=True, help_text='Free text pickup time', max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='preferred_datetime',
            field=models.CharField(blank=True, help_text='Half day: date + time', max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='pricing_selection',
            field=models.JSONField(blank=True, help_text='Snapshot from site: route, tier, price lines for WhatsApp parity', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='booking',
            name='selected_package_name',
            field=models.CharField(blank=True, help_text='Chosen package title if no FK', max_length=500),
        ),
        migrations.AddField(
            model_name='booking',
            name='selected_tours',
            field=models.JSONField(blank=True, default=list, help_text='List of tour names when booking_type=tour'),
        ),
        migrations.AddField(
            model_name='booking',
            name='special_requests',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='suitcases',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='tour_destination',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='booking',
            name='transfer_direction',
            field=models.CharField(blank=True, help_text='e.g. Airport to hotel / Hotel to airport', max_length=64),
        ),
        migrations.AddField(
            model_name='booking',
            name='transfer_segment',
            field=models.CharField(blank=True, choices=[('airport', 'Airport & hotel'), ('half_day', 'Half day'), ('full_day', 'Full day')], help_text='Which transfer form', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='transfer_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='safari.transferservice'),
        ),
        migrations.AddField(
            model_name='booking',
            name='transfer_time_note',
            field=models.CharField(blank=True, help_text='Full day: start window', max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='transport_needed',
            field=models.CharField(blank=True, help_text='Yes / No', max_length=8),
        ),
        migrations.AddField(
            model_name='package',
            name='description',
            field=models.TextField(blank=True, help_text='Long intro / marketing copy (desc on site)'),
        ),
        migrations.AddField(
            model_name='package',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='packages/'),
        ),
        migrations.AddField(
            model_name='package',
            name='hero_image_url',
            field=models.URLField(blank=True, help_text='If set, can be used instead of upload', max_length=2000),
        ),
        migrations.AddField(
            model_name='package',
            name='highlights',
            field=models.JSONField(blank=True, default=list, help_text='["bullet", ...]'),
        ),
        migrations.AddField(
            model_name='package',
            name='important_info',
            field=models.JSONField(blank=True, default=list, help_text='["note", ...]'),
        ),
        migrations.AddField(
            model_name='package',
            name='itinerary',
            field=models.JSONField(blank=True, default=list, help_text='["Day 1: ...", ...]'),
        ),
        migrations.AddField(
            model_name='package',
            name='price_groups',
            field=models.JSONField(blank=True, default=list, help_text='[{"title": "Best Value", "rows": [{"people": "...", "price": "..."}]}]'),
        ),
        migrations.AddField(
            model_name='package',
            name='prices',
            field=models.JSONField(blank=True, default=list, help_text='[{"people": "1 Person", "price": "$100"}, ...] when not using price_groups'),
        ),
        migrations.AddField(
            model_name='package',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL segment; auto from title if unset', max_length=280, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='package',
            name='special_offers',
            field=models.JSONField(blank=True, default=list, help_text='["offer line", ...]'),
        ),
        migrations.AddField(
            model_name='tour',
            name='bonuses',
            field=models.JSONField(blank=True, default=list, help_text='["bonus perk", ...] optional'),
        ),
        migrations.AddField(
            model_name='tour',
            name='description',
            field=models.TextField(blank=True, help_text='Main paragraph (desc)'),
        ),
        migrations.AddField(
            model_name='tour',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='tours/'),
        ),
        migrations.AddField(
            model_name='tour',
            name='hero_image_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='tour',
            name='highlights',
            field=models.JSONField(blank=True, default=list, help_text='["bullet", ...]'),
        ),
        migrations.AddField(
            model_name='tour',
            name='includes',
            field=models.TextField(blank=True, help_text='Comma-separated style sentence or bullet line'),
        ),
        migrations.AddField(
            model_name='tour',
            name='prices',
            field=models.JSONField(blank=True, default=list, help_text='[{"people": "1 Person", "price": "$50"}, ...]'),
        ),
        migrations.AddField(
            model_name='tour',
            name='slug',
            field=models.SlugField(blank=True, max_length=280, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transferservice',
            name='description',
            field=models.TextField(blank=True, help_text='Extra HTML-free copy for apps'),
        ),
        migrations.AddField(
            model_name='transferservice',
            name='pricing_payload',
            field=models.JSONField(blank=True, default=dict, help_text='e.g. airport_routes, half_day_tiers, full_day_tiers, includes, excludes, notes'),
        ),
        migrations.AddField(
            model_name='transferservice',
            name='slug',
            field=models.SlugField(blank=True, max_length=280, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='item_name',
            field=models.CharField(blank=True, help_text='Primary label / package title / transfer summary', max_length=500),
        ),
        migrations.AlterField(
            model_name='booking',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal staff notes'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='party_size',
            field=models.PositiveIntegerField(default=1, help_text='Total pax if not splitting adults/children'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='base_price',
            field=models.CharField(blank=True, help_text='Short headline price for cards e.g. TSh 1,196,000 per person (6+)', max_length=255),
        ),
        migrations.AlterField(
            model_name='tour',
            name='from_price',
            field=models.CharField(blank=True, help_text='Headline ‘from’ for listings', max_length=255),
        ),
        migrations.AlterField(
            model_name='transferservice',
            name='from_price',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
