"""Seed package content copied from frontend Packages page."""

from __future__ import annotations

from typing import Any


PACKAGE_SEED_DATA: list[dict[str, Any]] = [
    {
        "title": "8 Day Zanzibar Luxury Private Experience",
        "subtitle": "All inclusive tour - everything covered",
        "description": "Enjoy a complete Zanzibar experience with boat trip, hotel transfers, lunch & refreshments, all entrance fees, professional guide and entertainment.",
        "duration_days": 8,
        "status": "active",
        "base_price": "$460 per person (6+)",
        "highlights": [
            "Snorkeling at Mnemba Atoll with dolphins",
            "Prison Island - giant tortoise interaction",
            "Spice Farm - cooking class & tasting session",
            "Blue Safari luxury experience with sunset cruise",
            "Stone Town night street food tour",
            "Jozani Monkey Forest & mangrove boardwalk",
            "Nakupenda sandbank with drone photos",
        ],
        "itinerary": [
            "Day 1: VIP airport arrival & hotel transfer",
            "Day 2: Snorkeling at Mnemba Atoll with Dolphins",
            "Day 3: Spice farm + cooking class + night food tour",
            "Day 4: Luxury Blue Safari experience",
            "Day 5: Monkey forest + village cultural tour",
            "Day 6: Prison Island + Nakupenda Island",
            "Day 7: Free luxury day - spa, beach club, massage",
            "Day 8: VIP departure to airport",
        ],
        "prices": [
            {"people": "1 Person", "price": "$875 per person"},
            {"people": "2 People", "price": "$675 per person"},
            {"people": "3 People", "price": "$525 per person"},
            {"people": "4 People", "price": "$495 per person"},
            {"people": "5 People", "price": "$475 per person"},
            {"people": "6+ People", "price": "$460 per person"},
        ],
        "price_groups": [],
        "special_offers": [
            "Save up to $400 per person as a group",
            "Free drone photos & video in one trip",
            "Groups of 10+ get 15% discount",
        ],
        "important_info": [
            "Hotel accommodation not included",
            "Price depends on number of people",
            "Children accepted",
            "Private option available",
            "Daily departures",
        ],
        "hero_image_url": "",
    },
    {
        "title": "8 Day Zanzibar Combo Package",
        "subtitle": "Beach + Safari - one day Tanzania, seven days Zanzibar",
        "description": "A balanced package combining nature, ocean and culture. Game drive in national park plus snorkeling, street walks, cooking class and more.",
        "duration_days": 8,
        "status": "active",
        "base_price": "$670 per person (best value group)",
        "highlights": [
            "Snorkeling at Mnemba Atoll",
            "Stone Town street walk & food tour",
            "Spice Farm & cooking class",
            "Prison Island visit",
            "Nakupenda sandbank with drone photos",
            "Safari Blue luxury experience",
            "1 Day Safari Tanzania - lions, giraffes, elephants",
        ],
        "itinerary": [
            "Day 1: Arrival & beach relaxation",
            "Day 2: Spice farm + cooking class + night food tour",
            "Day 3: Snorkeling at Mnemba Atoll",
            "Day 4: Free day (beach, horse riding, jet ski)",
            "Day 5: Safari Tanzania - day trip",
            "Day 6: Free day to enjoy",
            "Day 7: Prison Island + Nakupenda sandbank",
            "Day 8: Departure & airport transfer",
        ],
        "prices": [],
        "price_groups": [
            {
                "title": "Best Value Group",
                "rows": [
                    {"people": "4 People", "price": "$735 per person"},
                    {"people": "5 People", "price": "$710 per person"},
                    {"people": "6 People", "price": "$670 per person"},
                ],
            },
            {
                "title": "Small Group",
                "rows": [
                    {"people": "2 People", "price": "$935 per person"},
                    {"people": "3 People", "price": "$835 per person"},
                ],
            },
            {"title": "Private Tour", "rows": [{"people": "1 Person", "price": "$1,235"}]},
        ],
        "special_offers": [
            "Save up to $400 per person as a group",
            "Free drone photos & video in one trip",
        ],
        "important_info": [
            "Includes domestic flight for safari, private boat, transfers, lunch, all entrance fees",
            "Hotel accommodation not included",
            "Children accepted",
            "Groups of 10+ get 10% discount",
        ],
        "hero_image_url": "",
    },
    {
        "title": "3 Day Serengeti Safari + 4 Day Zanzibar",
        "subtitle": "Serengeti + Zanzibar - wild beauty meets white sand beaches",
        "description": "Watch lions at sunrise in Serengeti and end your journey on white sand beaches of Zanzibar in one unforgettable experience.",
        "duration_days": 7,
        "status": "active",
        "base_price": "$1,925 per person (best value group)",
        "highlights": [
            "Serengeti: Full board accommodation, private guide, 4x4 game drive, Big 5 viewing",
            "Zanzibar: All inclusive tours, transfers, snorkeling with dolphins",
            "Seafood lunch & tropical fruits during excursions",
            "Prison Island visit & Stone Town experience",
        ],
        "itinerary": [
            "Day 1: Arrival in Arusha, transfer to Serengeti",
            "Day 2: Game drive at Serengeti",
            "Day 3: Bush adventures, fly to Zanzibar",
            "Day 4: Relaxation - free day in Zanzibar",
            "Day 5: Snorkeling + spice farm + cooking class",
            "Day 6: Stone Town tour + Prison Island",
            "Day 7: Departure",
        ],
        "prices": [],
        "price_groups": [
            {
                "title": "Best Value Group",
                "rows": [
                    {"people": "4 People", "price": "$1,960 per person"},
                    {"people": "5 People", "price": "$1,945 per person"},
                    {"people": "6 People", "price": "$1,925 per person"},
                ],
            },
            {
                "title": "Small Group",
                "rows": [
                    {"people": "2 People", "price": "$1,985 per person"},
                    {"people": "3 People", "price": "$1,980 per person"},
                ],
            },
            {"title": "Private Tour", "rows": [{"people": "1 Person", "price": "$2,000"}]},
        ],
        "special_offers": [
            "Save more than $400 as a group",
            "Drone photo & video in one excursion (Zanzibar only)",
        ],
        "important_info": [
            "Perfect for tourists who want everything in one trip",
            "Best for friends and families",
            "Suitable for couples, solo travelers, small groups",
        ],
        "hero_image_url": "",
    },
    {
        "title": "2 Day Zanzibar Cultural Experience",
        "subtitle": "Stone Town + Prison Island + Spice Farm + Cooking Class",
        "description": "Discover the beauty and history of Zanzibar in this unforgettable 2-day adventure. Best for families, couples, and groups.",
        "duration_days": 2,
        "status": "active",
        "base_price": "$70 per person (premium, 6 people)",
        "highlights": [
            "Stone Town historical walk",
            "Prison Island giant tortoise interaction",
            "Spice farm tour & cooking class",
            "Night street food tour",
        ],
        "itinerary": [],
        "prices": [],
        "price_groups": [
            {
                "title": "Luxury Package",
                "rows": [
                    {"people": "1 Person", "price": "$190"},
                    {"people": "2 People", "price": "$170 per person"},
                    {"people": "3 People", "price": "$150 per person"},
                    {"people": "4 People", "price": "$130 per person"},
                    {"people": "5 People", "price": "$100 per person"},
                    {"people": "6 People", "price": "$80 per person"},
                ],
            },
            {
                "title": "Premium Package",
                "rows": [
                    {"people": "1 Person", "price": "$170"},
                    {"people": "2 People", "price": "$150 per person"},
                    {"people": "3 People", "price": "$130 per person"},
                    {"people": "4 People", "price": "$110 per person"},
                    {"people": "5 People", "price": "$90 per person"},
                    {"people": "6 People", "price": "$70 per person"},
                ],
            },
        ],
        "special_offers": [
            "Free bottled water",
            "Free transfer service",
            "Free Zanzibar souvenir",
            "Free cooking class",
        ],
        "important_info": [],
        "hero_image_url": "",
    },
    {
        "title": "3 Day Zanzibar Snorkeling & Cultural Experience",
        "subtitle": "Mnemba dolphins + spice farm + cooking class + swim with tortoise",
        "description": "Snorkeling in Mnemba Atoll with dolphins, shopping in Stone Town, and learning to cook traditional Zanzibar dishes. Perfect mix of ocean, culture and food.",
        "duration_days": 3,
        "status": "active",
        "base_price": "$90 per person (6 people)",
        "highlights": [
            "Mnemba Atoll snorkeling with dolphins",
            "Spice farm & cooking class",
            "Stone Town shopping & culture",
            "Swim with tortoise",
        ],
        "itinerary": [],
        "prices": [
            {"people": "1 Person", "price": "$260"},
            {"people": "2 People", "price": "$200 per person"},
            {"people": "3 People", "price": "$180 per person"},
            {"people": "4 People", "price": "$160 per person"},
            {"people": "5 People", "price": "$110 per person"},
            {"people": "6 People", "price": "$90 per person"},
        ],
        "price_groups": [],
        "special_offers": [
            "Free bottled water",
            "Free local fruit tasting",
            "Free Zanzibar souvenir",
            "Free cooking class & photo editing",
        ],
        "important_info": [
            "Includes transfers, park fees, private car & boat, snorkeling gear, photographer, guide, seafood lunch"
        ],
        "hero_image_url": "",
    },
    {
        "title": "4 Day Dhow Cruise & Snorkeling Experience",
        "subtitle": "Blue safari + sandbank picnic + night food tour + swim with tortoise",
        "description": "Combining culture, adventure, and relaxation - perfect for travelers who want the complete Zanzibar experience.",
        "duration_days": 4,
        "status": "active",
        "base_price": "$200 per person (premium, 6+)",
        "highlights": [
            "Blue Safari with sunset cruise",
            "Spice farm + cooking class + Salaam cave",
            "Mnemba dolphin snorkeling",
            "Prison Island + Nakupenda sandbank",
        ],
        "itinerary": [
            "Day 1: Blue Safari",
            "Day 2: Spice farm + cooking class + Salaam cave",
            "Day 3: Mnemba dolphin + Stone Town street walk",
            "Day 4: Prison Island + Nakupenda sandbank",
        ],
        "prices": [],
        "price_groups": [
            {
                "title": "Luxury Package",
                "rows": [
                    {"people": "1 Person", "price": "$600"},
                    {"people": "2 People", "price": "$530 per person"},
                    {"people": "3 People", "price": "$470 per person"},
                    {"people": "4 People", "price": "$410 per person"},
                    {"people": "5 People", "price": "$300 per person"},
                    {"people": "6+ People", "price": "$250 per person"},
                ],
            },
            {
                "title": "Premium Package",
                "rows": [
                    {"people": "1 Person", "price": "$530"},
                    {"people": "2 People", "price": "$450 per person"},
                    {"people": "3 People", "price": "$400 per person"},
                    {"people": "4 People", "price": "$350 per person"},
                    {"people": "5 People", "price": "$250 per person"},
                    {"people": "6+ People", "price": "$200 per person"},
                ],
            },
        ],
        "special_offers": [
            "Free bottled water",
            "Free local fruit tasting",
            "Free Zanzibar souvenir",
            "Free cooking class",
            "Fresh coconut",
        ],
        "important_info": [],
        "hero_image_url": "",
    },
    {
        "title": "10 Day Authentic Local Life Experience",
        "subtitle": "Feel the rhythm of Zanzibar Island",
        "description": "Traditional dhow cruise, hidden sandbank picnic, snorkeling, cooking class, sightseeing, street walk, shopping and star fish.",
        "duration_days": 10,
        "status": "active",
        "base_price": "$300 per person (premium, 6+)",
        "highlights": [
            "Snorkeling with dolphins",
            "Monkey forest + spice farm + sunset cruise",
            "Safari blue",
            "Salaam cave + Stone Town",
            "Hidden sandbank + Prison Island",
            "Kendwa beach with optional rock restaurant",
        ],
        "itinerary": [
            "Day 1: Arrival at Zanzibar airport",
            "Day 2: Snorkeling with dolphins",
            "Day 3: Monkey forest + spice farm + sunset cruise",
            "Day 4: Free day",
            "Day 5: Safari Blue",
            "Day 6: Salaam cave + Stone Town tour",
            "Day 7: Hidden sandbank + Prison Island",
            "Day 8: Free day",
            "Day 9: Kendwa beach",
            "Day 10: Departure",
        ],
        "prices": [],
        "price_groups": [
            {
                "title": "Premium Package",
                "rows": [
                    {"people": "1 Person", "price": "$830"},
                    {"people": "2 People", "price": "$700 per person"},
                    {"people": "3 People", "price": "$600 per person"},
                    {"people": "4 People", "price": "$500 per person"},
                    {"people": "5 People", "price": "$400 per person"},
                    {"people": "6+ People", "price": "$300 per person"},
                ],
            },
            {
                "title": "Luxury Package",
                "rows": [
                    {"people": "1 Person", "price": "$930"},
                    {"people": "2 People", "price": "$800 per person"},
                    {"people": "3 People", "price": "$700 per person"},
                    {"people": "4 People", "price": "$600 per person"},
                    {"people": "5 People", "price": "$500 per person"},
                    {"people": "6+ People", "price": "$400 per person"},
                ],
            },
        ],
        "special_offers": [
            "Free transfer (arrival to departure)",
            "Bottled water",
            "Free fruit tasting",
            "Zanzibar souvenir",
            "Free cooking class",
            "Fresh coconut",
            "Drone couple photos",
        ],
        "important_info": [],
        "hero_image_url": "",
    },
]
