"""Seed tour content copied from frontend Tours page."""

from __future__ import annotations

from typing import Any


TOUR_SEED_DATA: list[dict[str, Any]] = [
    {
        "title": "Day in the Life - Village Immersion",
        "category": "Culture",
        "description": "Authentic Swahili home cooking, village and spice immersion, and cooking class. Escape the hotel and journey into the heart of Swahili culture.",
        "includes": "Authentic village lunch, taxi, supporting hosting family, private guide",
        "highlights": [
            "See local women prepare chicken soup",
            "Prepare coconut sauce traditionally",
            "Bush pharmacy & traditional medicine",
            "Swahili kitchen: pilau, fresh fish, coconut rice over open fire",
        ],
        "bonuses": [],
        "prices": [
            {"people": "1 Person", "price": "$130"},
            {"people": "2 People", "price": "$75 per person"},
            {"people": "3 People", "price": "$60 per person"},
            {"people": "4 People", "price": "$50 per person"},
            {"people": "5 People", "price": "$40 per person"},
            {"people": "6+ People", "price": "$30 per person"},
        ],
        "from_price": "$30 per person",
        "status": "active",
        "hero_image_url": "",
    },
    {
        "title": "Stone Town + Prison Island",
        "category": "Culture & History",
        "description": "Giant tortoise interaction, city tour, secret doors and hidden alleys, rooftop sunset views away from the crowds.",
        "includes": "Private luxury boat, entrance fees, taxi, private guide",
        "highlights": [
            "Africa giant tortoise interaction",
            "Street walk city tour",
            "Secret doors & hidden alleys",
            "Sunset views away from crowds",
        ],
        "bonuses": ["Free spice farm tour", "Refreshment", "Zanzibar souvenir", "Professional photographer"],
        "prices": [
            {"people": "1 Person", "price": "$150"},
            {"people": "2 People", "price": "$120 per person"},
            {"people": "3 People", "price": "$90 per person"},
            {"people": "4 People", "price": "$75 per person"},
            {"people": "5 People", "price": "$60 per person"},
            {"people": "6+ People", "price": "$50 per person"},
        ],
        "from_price": "$50 per person",
        "status": "active",
        "hero_image_url": "",
    },
    {
        "title": "Stone Town + Prison Island + Nakupenda",
        "category": "Culture & Sandbank",
        "description": "Hidden sandbank picnic, giant tortoise interaction, and a full city tour with premium seafood lunch setup.",
        "includes": "Private luxury boat, entrance fees, taxi, private guide, seafood lunch",
        "highlights": [
            "Hidden sandbank picnic",
            "Giant tortoise experience",
            "Stone Town city tour",
            "Seafood lunch with premium setup",
        ],
        "bonuses": ["Tropical fruits & refreshments", "Zanzibar souvenir", "Professional photographer"],
        "prices": [
            {"people": "1 Person", "price": "$210"},
            {"people": "2 People", "price": "$115 per person"},
            {"people": "3 People", "price": "$100 per person"},
            {"people": "4 People", "price": "$90 per person"},
            {"people": "5 People", "price": "$80 per person"},
            {"people": "6+ People", "price": "$70 per person"},
        ],
        "from_price": "$70 per person",
        "status": "active",
        "hero_image_url": "",
    },
    {
        "title": "Mnemba Island Luxury Experience",
        "category": "Ocean & Snorkeling",
        "description": "Snorkeling with dolphins in crystal clear turquoise waters, hidden sandbank picnic with seafood lunch.",
        "includes": "Private luxury boat, entrance fees, taxi, private guide, seafood lunch",
        "highlights": [
            "Snorkeling with dolphins",
            "Hidden sandbank picnic",
            "Crystal clear waters",
            "Vibrant coral reef",
        ],
        "bonuses": ["Refreshment", "Zanzibar souvenir", "Tropical fruits", "Professional photographer"],
        "prices": [
            {"people": "1 Person", "price": "$180"},
            {"people": "2 People", "price": "$100 per person"},
            {"people": "3 People", "price": "$80 per person"},
            {"people": "4 People", "price": "$70 per person"},
            {"people": "5 People", "price": "$60 per person"},
            {"people": "6+ People", "price": "$50 per person"},
        ],
        "from_price": "$50 per person",
        "status": "active",
        "hero_image_url": "",
    },
    {
        "title": "Luxury Blue Safari Experience",
        "category": "Ocean Adventure",
        "description": "Private boat, coral reef snorkelling, blue lagoon swim, sandbank picnic, sunset cruise, Swahili seafood BBQ, star fish and beach relaxation.",
        "includes": "Private luxury boat, entrance fees, taxi, private guide, seafood lunch",
        "highlights": [
            "Snorkelling in coral reefs",
            "Swim in blue lagoon",
            "Sunset cruise",
            "Swahili seafood BBQ lunch",
        ],
        "bonuses": ["Refreshments", "Zanzibar souvenir"],
        "prices": [
            {"people": "1 Person", "price": "$180"},
            {"people": "2 People", "price": "$100 per person"},
            {"people": "3 People", "price": "$80 per person"},
            {"people": "4 People", "price": "$70 per person"},
            {"people": "5 People", "price": "$60 per person"},
            {"people": "6+ People", "price": "$50 per person"},
        ],
        "from_price": "$50 per person",
        "status": "active",
        "hero_image_url": "",
    },
    {
        "title": "Stone Town + Spice Farm",
        "category": "Culture",
        "description": "Village walks, cooking class, and night street food tour in Stone Town.",
        "includes": "Entrance fees, taxi, private guide, refreshment",
        "highlights": ["Village walks & spice farm", "Cooking class", "Night street food tour"],
        "bonuses": ["Free lunch at spice farm", "Zanzibar souvenir"],
        "prices": [
            {"people": "1 Person", "price": "$130"},
            {"people": "2 People", "price": "$110 per person"},
            {"people": "3 People", "price": "$90 per person"},
            {"people": "4 People", "price": "$60 per person"},
            {"people": "5 People", "price": "$50 per person"},
            {"people": "6+ People", "price": "$40 per person"},
        ],
        "from_price": "$40 per person",
        "status": "active",
        "hero_image_url": "",
    },
    {
        "title": "Sport Fishing Adventure",
        "category": "Adventure",
        "description": "Deep-sea fishing with professional local captains. Catch tuna, sailfish, kingfish and more. Includes all equipment, boat, safety gear and refreshments.",
        "includes": "Fishing boat, equipment, captain, safety gear, refreshments",
        "highlights": [
            "Professional fishing equipment",
            "Experienced local captain",
            "Snorkeling & swimming",
            "Village fish market visit",
        ],
        "bonuses": ["Zanzibar souvenir", "One whole fish from village market", "Free fish cooking class"],
        "prices": [
            {"people": "1 Person (private boat)", "price": "$450"},
            {"people": "2 People (sharing)", "price": "$470 total"},
            {"people": "3 People (sharing)", "price": "$490 total"},
            {"people": "4 People (sharing)", "price": "$500 total"},
        ],
        "from_price": "$450",
        "status": "active",
        "hero_image_url": "",
    },
]
